"""
Subgrid Projector Splitter Engine.
Decomposes complex multi-grid vessels (rotors, hinges, pistons, turrets) into standalone
projector-printable sub-blueprints with step-by-step survival shipyard assembly instructions.
"""

from __future__ import annotations
import copy
from dataclasses import dataclass, field
from pathlib import Path
import re
from typing import Dict, List, Optional
import xml.etree.ElementTree as ET
import safe_xml
from subgrid_engine.hierarchy_parser import SubgridHierarchyParser, SubgridNode


@dataclass
class SplitBlueprintEntry:
    """Details for an individual decomposed sub-blueprint."""
    sequence_number: int
    grid_name: str
    grid_size: str
    block_count: int
    attachment_point: Optional[str]
    blueprint_dir: Path
    sbc_path: Path


@dataclass
class ProjectorSplitResult:
    """Result summary of a multi-grid projector decomposition."""
    success: bool
    source_blueprint_name: str
    total_subgrids: int
    output_directory: Path
    sub_blueprints: List[SplitBlueprintEntry] = field(default_factory=list)
    assembly_guide_path: Optional[Path] = None
    assembly_guide_text: str = ""
    error_message: Optional[str] = None


class ProjectorSplitter:
    """Splits multi-grid Space Engineers blueprints into projector-friendly standalone blueprints."""

    @classmethod
    def split_blueprint(
        cls,
        source_bp_path: Path,
        output_parent_dir: Optional[Path] = None,
    ) -> ProjectorSplitResult:
        source_bp_path = Path(source_bp_path)
        if source_bp_path.is_dir():
            sbc_file = source_bp_path / "bp.sbc"
            bp_name = source_bp_path.name
        else:
            sbc_file = source_bp_path
            bp_name = source_bp_path.parent.name if source_bp_path.name == "bp.sbc" else source_bp_path.stem

        if not sbc_file.is_file():
            return ProjectorSplitResult(
                success=False,
                source_blueprint_name=bp_name,
                total_subgrids=0,
                output_directory=source_bp_path,
                error_message=f"Blueprint SBC file not found at: {sbc_file}",
            )

        try:
            tree = safe_xml.parse(sbc_file)
            root = tree.getroot()
        except Exception as exc:
            return ProjectorSplitResult(
                success=False,
                source_blueprint_name=bp_name,
                total_subgrids=0,
                output_directory=source_bp_path,
                error_message=f"Failed to parse XML: {exc}",
            )

        cube_grids = root.findall(".//CubeGrid")
        if not cube_grids:
            return ProjectorSplitResult(
                success=False,
                source_blueprint_name=bp_name,
                total_subgrids=0,
                output_directory=source_bp_path,
                error_message="No CubeGrid elements found in blueprint.",
            )

        if len(cube_grids) == 1:
            return ProjectorSplitResult(
                success=True,
                source_blueprint_name=bp_name,
                total_subgrids=1,
                output_directory=source_bp_path,
            )

        # Parse hierarchy to determine order
        hierarchy = SubgridHierarchyParser.parse_element(root)

        if output_parent_dir is None:
            output_parent_dir = source_bp_path.parent if source_bp_path.is_file() else source_bp_path.parent

        safe_bp_name = re.sub(r'[\\/*?:"<>|]', "_", bp_name)
        target_split_dir = output_parent_dir / f"PRINTABLE_{safe_bp_name}"
        target_split_dir.mkdir(parents=True, exist_ok=True)

        # Index grids by EntityId and name
        grid_by_id: Dict[str, ET.Element] = {}
        for cg in cube_grids:
            gid = cls._get_text(cg, "EntityId") or f"grid_{id(cg)}"
            grid_by_id[gid] = cg

        ordered_nodes: List[tuple[SubgridNode, int]] = []
        seq = 1

        def collect_nodes(node: SubgridNode, depth: int = 0):
            nonlocal seq
            ordered_nodes.append((node, seq))
            seq += 1
            for ch in node.children:
                collect_nodes(ch, depth + 1)

        if hierarchy.root_node:
            collect_nodes(hierarchy.root_node, 0)
        for orphan in hierarchy.orphaned_grids:
            collect_nodes(orphan, 0)

        entries: List[SplitBlueprintEntry] = []
        guide_lines: List[str] = [
            f"# SURVIVAL SHIPYARD PRINTING GUIDE: {bp_name}",
            f"Total Printable Sub-Blueprints: {len(ordered_nodes)}",
            "Generated by Space Engineers Tactical Command (SE-Block-Exchanger)",
            "",
            "## 🛠️ RECOMMENDED FABRICATION SEQUENCE",
            "Follow this numbered sequence to print and assemble your multi-grid vessel in survival mode:",
            "",
        ]

        for node, seq_num in ordered_nodes:
            grid_elem = grid_by_id.get(node.entity_id)
            if grid_elem is None:
                # Find by name fallback
                matching = [cg for cg in cube_grids if (cls._get_text(cg, "CustomName") or "") == node.grid_name]
                if matching:
                    grid_elem = matching[0]

            if grid_elem is None:
                continue

            clean_grid_name = re.sub(r'[\\/*?:"<>|]', "_", node.grid_name)
            folder_name = f"{seq_num:02d}_{'MAIN_HULL' if node.is_main_grid else clean_grid_name}"
            sub_bp_dir = target_split_dir / folder_name
            sub_bp_dir.mkdir(parents=True, exist_ok=True)
            sub_sbc_file = sub_bp_dir / "bp.sbc"

            # Construct clean standalone XML document.
            # Use Clark notation so ElementTree binds xmlns:xsi instead of
            # emitting a literal "xsi:type" attribute with no namespace.
            xsi_ns = "http://www.w3.org/2001/XMLSchema-instance"
            xsd_ns = "http://www.w3.org/2001/XMLSchema"
            ET.register_namespace("xsi", xsi_ns)
            ET.register_namespace("xsd", xsd_ns)
            standalone_root = ET.Element("Definitions")

            sbps = ET.SubElement(standalone_root, "ShipBlueprints")
            sbp = ET.SubElement(sbps, "ShipBlueprint")
            sbp.set(f"{{{xsi_ns}}}type", "MyObjectBuilder_ShipBlueprintDefinition")

            id_elem = ET.SubElement(sbp, "Id")
            id_elem.set("Type", "MyObjectBuilder_ShipBlueprintDefinition")
            id_elem.set("Subtype", f"{safe_bp_name}_{folder_name}")

            display_name = ET.SubElement(sbp, "DisplayName")
            display_name.text = f"[{seq_num:02d}] {node.grid_name}"

            cube_grids_elem = ET.SubElement(sbp, "CubeGrids")
            
            # Deep-copy single grid element
            copied_grid = copy.deepcopy(grid_elem)
            cube_grids_elem.append(copied_grid)

            # Write standalone SBC
            tree_out = ET.ElementTree(standalone_root)
            ET.indent(tree_out, space="  ", level=0)
            safe_xml.safe_write(tree_out, sub_sbc_file)

            entry = SplitBlueprintEntry(
                sequence_number=seq_num,
                grid_name=node.grid_name,
                grid_size=node.grid_size,
                block_count=node.block_count,
                attachment_point=node.attachment_via,
                blueprint_dir=sub_bp_dir,
                sbc_path=sub_sbc_file,
            )
            entries.append(entry)

            # Assembly Guide Steps
            if node.is_main_grid:
                guide_lines.append(f"### STEP 1: Main Ship Hull — `{folder_name}`")
                guide_lines.append(f"- **Grid Size**: {node.grid_size} Grid | **Blocks**: {node.block_count:,}")
                guide_lines.append("- **Action**: Load into your primary shipyard projector and weld the entire main hull first.")
                guide_lines.append("- **Note**: Rotor bases, hinge bases, and piston bases will be welded in place during this step.")
                guide_lines.append("")
            else:
                guide_lines.append(f"### STEP {seq_num}: Subgrid Module — `{folder_name}`")
                guide_lines.append(f"- **Subgrid**: {node.grid_name} ({node.grid_size} Grid, {node.block_count:,} blocks)")
                guide_lines.append(f"- **Attached Via**: {node.attachment_via or 'Mechanical Joint'}")
                guide_lines.append("- **Action**:")
                guide_lines.append("  1. In Space Engineers, select the corresponding Rotor/Hinge base on your welded hull.")
                guide_lines.append("  2. In the terminal, click 'Add Small Head' or 'Add Rotor Top'.")
                guide_lines.append(f"  3. Attach a Projector block to the rotor/hinge head and load `{folder_name}`.")
                guide_lines.append("  4. Adjust projector offsets until the subgrid connects to the head, then weld completely.")
                guide_lines.append("")

        guide_lines.append("---")
        guide_lines.append("✓ Fabrication blueprint set ready for survival printing!")
        guide_text = "\n".join(guide_lines)

        guide_file = target_split_dir / "PRINTING_GUIDE.md"
        with open(guide_file, "w", encoding="utf-8") as gf:
            gf.write(guide_text)

        return ProjectorSplitResult(
            success=True,
            source_blueprint_name=bp_name,
            total_subgrids=len(entries),
            output_directory=target_split_dir,
            sub_blueprints=entries,
            assembly_guide_path=guide_file,
            assembly_guide_text=guide_text,
        )

    @staticmethod
    def _get_text(element: ET.Element, tag: str) -> Optional[str]:
        child = element.find(tag)
        if child is not None and child.text:
            return child.text.strip()
        return None
